image: debian


before_script:
  - apt-get update
  - apt-get install -y gcc g++ make libsubunit-dev libsubunit0 check python3 python3-pip
  - pip3 install gcovr


compile:
  script:
  - make
  - ./memory_tests
  artifacts:
    paths:
    - coverage_report.src_memory_management.c.html
    - test.log
